name: Build Sing-Box

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get latest commit ID
        run: |
          git fetch origin dev-next
          COMMIT_ID=$(git rev-parse origin/dev-next)

      - name: Compile Sing-Box
        run: |
          cd sing-box/cmd/sing-box
          go install -v -tags "with_clash_api with_grpc with_wireguard with_utls with_gvisor with_quic with_dhcp with_ech with_reality_server" github.com/sagernet/sing-box/cmd/sing-box@$COMMIT_ID
