name: Build Sing-Box

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone Sing-Box repository
        uses: actions/checkout@v2
        with:
          repository: sagernet/sing-box
          ref: dev-next
          path: sing-box

      - name: Set up Go environment
        run: |
          mkdir -p $HOME/go/bin
          echo "export GOPATH=$HOME/go" >> $HOME/.bashrc
          echo "export PATH=\$PATH:\$GOPATH/bin" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Restore commit ID cache
        uses: actions/cache@v2
        id: commit-cache
        with:
          path: sing-box/.commit_id_cache
          key: ${{ runner.os }}-commit-id-${{ hashFiles('sing-box/go.mod') }}

      - name: Get latest commit ID
        if: steps.commit-cache.cache-hit != 'true'
        run: |
          cd sing-box
          git fetch origin dev-next
          COMMIT_ID=$(git rev-parse --short origin/dev-next)
          echo "Using commit ID: $COMMIT_ID"
          echo "$COMMIT_ID" > .commit_id_cache

      - name: Compile Sing-Box
        run: |
          cd sing-box
          COMMIT_ID=$(cat .commit_id_cache)
          go build -ldflags "-X main.Version=$COMMIT_ID" -o sing-box ./cmd/sing-box
          echo "Built Sing-Box with commit ID $COMMIT_ID"
